site_name: Documentation/ Notes
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - mkdocstrings

nav:
  - Home: index.md  # Example homepage

  # Include all folders and files in the docs directory
  - Date Manager:
      - Date Manager/index.md
      - Date Manager/tutorials.md
      - Date Manager/how-to-guides.md
      - Date Manager/reference.md
      - Date Manager/explanation.md
      - Date Manager/DateManager.md
  - Excel Manager:
      - Excel Manager/index.md
      - Excel Manager/tutorials.md
      - Excel Manager/how-to-guides.md
      - Excel Manager/reference.md
      - Excel Manager/explanation.md
      - Excel Manager/ExcelManager.md
  - Mail Manager:
      - Mail Manager/index.md
      - Mail Manager/tutorials.md
      - Mail Manager/how-to-guides.md
      - Mail Manager/reference.md
      - Mail Manager/explanation.md
      - Mail Manager/MailManager.md
  - Log Manager:
      - Log Manager/index.md
      - Log Manager/tutorials.md
      - Log Manager/how-to-guides.md
      - Log Manager/reference.md
      - Log Manager/explanation.md
      - Log Manager/LogManager.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ronakr14

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      
copyright: |
  &copy; 2024 <a href="https://github.com/ronakr14"  target="_blank" rel="noopener">Ronak Rathore</a>